import syntaxHighlight from "@11ty/eleventy-plugin-syntaxhighlight";
import { readingTime, findProjectsByIds, validateBlogPost } from './lib/filters.js';
import fs from 'fs';

export default function(eleventyConfig) {
  // Ignore non-content directories
  eleventyConfig.ignores.add("_bmad/**");
  eleventyConfig.ignores.add("_bmad-output/**");
  eleventyConfig.ignores.add("src/**");
  eleventyConfig.ignores.add("node_modules/**");
  eleventyConfig.ignores.add("docs/**");
  eleventyConfig.ignores.add("scripts/**");

  // React-era content (has Prometheus/Jinja2 syntax that conflicts with Nunjucks)
  // Will be migrated in future story with proper escaping
  eleventyConfig.ignores.add("content/blog/**");
  eleventyConfig.ignores.add("content/projects/**");
  eleventyConfig.ignores.add("content/config/**");

  // Ignore public directory templates (passthrough copy only)
  eleventyConfig.ignores.add("public/**");

  // Ignore React SPA entry point
  eleventyConfig.ignores.add("index.html");

  // Ignore Claude Code configuration
  eleventyConfig.ignores.add(".claude/**");

  // Ignore README files (shouldn't be published as pages)
  eleventyConfig.ignores.add("README.md");
  eleventyConfig.ignores.add("tests/**/*.md");

  // Syntax highlighting for code blocks
  // tabindex enables keyboard users to scroll code blocks
  eleventyConfig.addPlugin(syntaxHighlight, {
    preAttributes: {
      tabindex: 0
    }
  });

  // Date filter for formatting dates (default: "Jan 15, 2026" format)
  // Uses UTC to avoid timezone-related date shifts
  eleventyConfig.addFilter("date", (dateObj, format) => {
    if (!dateObj) return '';
    const date = new Date(dateObj);
    if (format === '%Y-%m-%d') {
      return date.toISOString().split('T')[0];
    }
    // Use UTC methods to avoid timezone shifts
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const monthsFull = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const month = date.getUTCMonth();
    const day = date.getUTCDate();
    const year = date.getUTCFullYear();
    if (format === '%B %d, %Y') {
      return `${monthsFull[month]} ${day}, ${year}`;
    }
    // Default: "Jan 15, 2026" format (matches React implementation)
    return `${months[month]} ${day}, ${year}`;
  });

  // Get category from tags for blog posts (matches React getCategoryFromTags logic)
  eleventyConfig.addFilter("getCategoryFromTags", (tags) => {
    if (!tags || !Array.isArray(tags)) return 'GENERAL';
    if (tags.some(t => t.toLowerCase().includes('opinion'))) return 'OPINION';
    if (tags.some(t => t.toLowerCase().includes('technical'))) return 'TECHNICAL';
    if (tags.some(t => t.toLowerCase().includes('tutorial'))) return 'TUTORIAL';
    return 'GENERAL';
  });

  // Filter to get items where a data attribute is truthy
  eleventyConfig.addFilter("where", (array, key) => {
    if (!array) return [];
    return array.filter(item => {
      const keys = key.split('.');
      let value = item;
      for (const k of keys) {
        value = value?.[k];
      }
      return !!value;
    });
  });

  // Filter to take first N items
  eleventyConfig.addFilter("take", (array, count) => {
    if (!array) return [];
    return array.slice(0, count);
  });

  // Reading time filter - imported from lib/filters.js for testability
  eleventyConfig.addFilter("readingTime", readingTime);

  // Find projects by their IDs - imported from lib/filters.js for testability
  eleventyConfig.addFilter("findProjectsByIds", findProjectsByIds);

  // Transform to replace mermaid code blocks with pre-rendered SVG images
  // This runs after HTML is generated, replacing <pre><code class="language-mermaid">
  // blocks with <img> tags pointing to SVGs generated by scripts/render-mermaid.js
  eleventyConfig.addTransform("mermaid-to-svg", function(content, outputPath) {
    // Only process HTML files
    if (!outputPath || !outputPath.endsWith(".html")) {
      return content;
    }

    // Process blog posts and project pages (not listing pages)
    const isBlogPost = outputPath.includes("/blog/") && !outputPath.endsWith("/blog/index.html");
    const isProjectPage = outputPath.includes("/projects/") && !outputPath.endsWith("/projects/index.html");

    if (!isBlogPost && !isProjectPage) {
      return content;
    }

    // Try to load the manifest
    const manifestPath = '_site/diagrams/manifest.json';
    if (!fs.existsSync(manifestPath)) {
      return content;
    }

    let manifest;
    try {
      manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    } catch (e) {
      return content;
    }

    // Extract content ID from output path
    let contentId;
    if (isBlogPost) {
      const match = outputPath.match(/\/blog\/([^/]+)\//);
      contentId = match ? match[1] : null;
    } else {
      const match = outputPath.match(/\/projects\/([^/]+)\//);
      contentId = match ? match[1] : null;
    }

    if (!contentId) {
      return content;
    }

    // Check if this content has inline diagrams in the manifest
    if (!manifest[contentId] || manifest[contentId].length === 0) {
      return content;
    }

    // Replace mermaid code blocks with img tags
    // The syntax highlighting plugin renders them as <pre><code class="language-mermaid">...</code></pre>
    let diagramIndex = 0;
    const mermaidBlockRegex = /<pre[^>]*><code class="language-mermaid"[^>]*>[\s\S]*?<\/code><\/pre>/g;

    content = content.replace(mermaidBlockRegex, (match) => {
      const diagram = manifest[contentId][diagramIndex];
      if (!diagram) {
        return match; // Keep original if no diagram found
      }

      diagramIndex++;

      // Return an img tag wrapped in a clickable container with diagram viewer
      return `<div class="my-8 relative" data-diagram-viewer>
        <div class="bg-white border-4 border-black p-6 flex justify-center" style="box-shadow: 8px 8px 0 #000;">
          <img
            src="${diagram.svgPath}"
            alt="Architecture diagram"
            class="max-w-full h-auto"
            loading="lazy"
          >
        </div>
        <span class="diagram-expand-hint">Click to expand</span>
      </div>`;
    });

    return content;
  });

  // Passthrough copy for static assets
  eleventyConfig.addPassthroughCopy("public");
  eleventyConfig.addPassthroughCopy("js");

  // Blog posts collection (using _content directory for 11ty-compatible content)
  // Includes frontmatter validation per Story 5.1 AC6
  eleventyConfig.addCollection("posts", collection => {
    const posts = collection.getFilteredByGlob("_content/blog/*.md");

    // Validate each post's frontmatter
    for (const post of posts) {
      const result = validateBlogPost(post.data, post.inputPath);
      if (!result.valid) {
        throw new Error(`Blog post validation failed:\n${result.errors.join('\n')}`);
      }
    }

    return posts;
  });

  // Projects collection (using _content directory for 11ty-compatible content)
  eleventyConfig.addCollection("projects", collection => {
    return collection.getFilteredByGlob("_content/projects/*.md");
  });

  return {
    dir: {
      input: ".",
      includes: "_includes",
      data: "_data",
      output: "_site"
    },
    templateFormats: ["njk", "md", "html"],
    markdownTemplateEngine: "njk",
    htmlTemplateEngine: "njk"
  };
}
